fun main(){
    println("student enrollment number: ")
    val enno=readln()
    println("student Name: ")
    val name=readln()
    println("student Branch: ")
    val branch=readln()
    println("student Class: ")
    val classname=readln()
    println("student Batch: ")
    val batch = readln()
    println("student College Name: ")
    val collegeName=readln()
    println("student University: ")
    val university=readln()
    println("student Age: ")
    val age=readln()
    println("Student Details:-\n Enrollment No.: $enno \n Name: $name \n Branch: $branch \n Class: $classname \n University: $university \n Age: $age ")
}